FROM python:3.13-slim AS builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    curl \
    gcc \
    g++ \
    iputils-ping \
    libpq-dev \
    python3-pip \
    python3-wheel \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home myuser

RUN python -m venv /home/myuser/venv
ENV PATH="/home/myuser/venv/bin:$PATH"

WORKDIR /home/myuser/app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir wheel && \
    pip install --no-cache-dir -r requirements.txt

FROM python:3.13-slim AS runner

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    iputils-ping \
    locales \
    net-tools \
    tzdata \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=${LOCALE_LANGUAGE}.utf8 \
    APP_DIR=/home/appuser/app \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/home/appuser/venv/bin:$PATH" \
    VIRTUAL_ENV=/home/appuser/venv

COPY --from=builder /home/myuser/venv /home/appuser/venv
COPY --from=builder /home/myuser/app /home/appuser/app

ENV WAIT_VERSION=2.12.0
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

RUN groupadd -r appgroup && \
    useradd -u 1000 --create-home appuser --no-log-init -g appgroup --shell /bin/bash --groups sudo && \
    mkdir -p /opt/cdrfiles /opt/cdrfiles_archives && \
    chown -R appuser:appgroup /opt/cdrfiles /opt/cdrfiles_archives && \
    chmod -R 777 ${APP_DIR} /opt/cdrfiles /opt/cdrfiles_archives

WORKDIR ${APP_DIR}

EXPOSE 5000