"""link extensions and queues to events bis

Revision ID: 25c2c8d021a3
Revises: d71140625354
Create Date: 2024-12-31 15:18:17.766260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '25c2c8d021a3'
down_revision = 'd71140625354'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Création de la table queues_events si elle n'existe pas déjà
    if 'queues_events' not in existing_tables:
        op.create_table('queues_events',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('queue_id', sa.Integer(), nullable=False),
            sa.Column('event_id', sa.Integer(), nullable=False),
            sa.Column('date_added', sa.DateTime(), nullable=True),
            sa.Column('date_modified', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['event_id'], ['extraevents.id'], name=op.f('fk_queues_events_event_id_extraevents')),
            sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_queues_events_queue_id_queues')),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_queues_events'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queues_events')
    # ### end Alembic commands ###