"""Change exdate to datetime

Revision ID: 315735431c93
Revises: 7d3ece5c0869
Create Date: 2025-03-01 16:49:56.741639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect, text
import logging

# Set up logging
logger = logging.getLogger('alembic.migration')

# revision identifiers, used by Alembic.
revision = '315735431c93'
down_revision = '7d3ece5c0869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Vérifier si la table et la colonne existent
    inspector = inspect(conn)
    if 'extraevents' not in inspector.get_table_names():
        logger.info("Table 'extraevents' does not exist, skipping column type change")
        return
        
    columns = [col['name'] for col in inspector.get_columns('extraevents')]
    if 'exdate' not in columns:
        logger.info("Column 'exdate' does not exist in table 'extraevents', skipping column type change")
        return
        
    # Vérifier le type actuel de la colonne exdate avec une requête plus précise pour PostgreSQL
    logger.info("Checking data type of column 'exdate' in table 'extraevents'")
    result = conn.execute(text("""
        SELECT data_type, udt_name 
        FROM information_schema.columns 
        WHERE table_name = 'extraevents' AND column_name = 'exdate'
    """)).fetchone()
    
    # Pour les colonnes de type ARRAY, PostgreSQL stocke '_date' dans udt_name pour ARRAY(DATE)
    if result and (result[0] == 'ARRAY' and result[1] == '_date'):
        logger.info("Column 'exdate' is of type ARRAY(DATE), converting to ARRAY(DateTime)")
        with op.batch_alter_table('extraevents', schema=None) as batch_op:
            batch_op.alter_column('exdate',
                    existing_type=postgresql.ARRAY(sa.DATE()),
                    type_=postgresql.ARRAY(sa.DateTime()),
                    existing_nullable=True)
        logger.info("Successfully converted column 'exdate' to ARRAY(DateTime)")
    else:
        if result:
            logger.info(f"Column 'exdate' is already of type {result[0]}/{result[1]}, no conversion needed")
        else:
            logger.info("Could not determine the type of column 'exdate', skipping conversion")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Converting column 'exdate' back to ARRAY(DATE)")
    try:
        with op.batch_alter_table('extraevents', schema=None) as batch_op:
            batch_op.alter_column('exdate',
                    existing_type=postgresql.ARRAY(sa.DateTime()),
                    type_=postgresql.ARRAY(sa.DATE()),
                    existing_nullable=True)
        logger.info("Successfully converted column 'exdate' back to ARRAY(DATE)")
    except Exception as e:
        logger.error(f"Error converting column 'exdate': {str(e)}")
    # ### end Alembic commands ###