"""add color on event types

Revision ID: 4a6d3c1ea7ba
Revises: e7592542da3c
Create Date: 2025-01-25 18:19:25.340388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '4a6d3c1ea7ba'
down_revision = 'e7592542da3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Vérifier si la colonne existe déjà avant de l'ajouter
    columns = [col['name'] for col in inspector.get_columns('events_types')]
    if 'color' not in columns:
        with op.batch_alter_table('events_types', schema=None) as batch_op:
            batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_types', schema=None) as batch_op:
        batch_op.drop_column('color')
    # ### end Alembic commands ###