"""modif events table

Revision ID: 4f38c31ac5e0
Revises: ae67969701ee
Create Date: 2024-08-13 17:31:54.418478

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f38c31ac5e0'
down_revision = 'ae67969701ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('event_tile')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_tile', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('event_title')

    # ### end Alembic commands ###
