"""Add date modified to queue and extensions

Revision ID: 6888c15df252
Revises: b48138200c75
Create Date: 2024-07-31 17:10:48.470076

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6888c15df252'
down_revision = 'b48138200c75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.Date(), nullable=True))

    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_modified', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_column('date_modified')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
