"""add recurrence rules to events

Revision ID: 7d3ece5c0869
Revises: bd81eaa71511
Create Date: 2025-03-01 15:56:38.913894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '7d3ece5c0869'
down_revision = 'bd81eaa71511'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    # Vérifier si la colonne existe déjà avant de l'ajouter
    columns = [col['name'] for col in inspector.get_columns('extraevents')]
    if 'exdate' not in columns:
        with op.batch_alter_table('extraevents', schema=None) as batch_op:
            batch_op.add_column(sa.Column('exdate', postgresql.ARRAY(sa.Date()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.drop_column('exdate')
    # ### end Alembic commands ###