"""Ajout semaine d'appel

Revision ID: 878e19eed77b
Revises: 841e980f9b6b
Create Date: 2023-06-06 10:03:53.529457

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '878e19eed77b'
down_revision = '841e980f9b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('call_data_records', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                autoincrement=True)

    with op.batch_alter_table('call_data_records_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
#         batch_op.alter_column('id',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                autoincrement=True)

#     with op.batch_alter_table('extensions', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                autoincrement=True)

#     with op.batch_alter_table('extensiontoqueuelink', schema=None) as batch_op:
#         batch_op.alter_column('extension_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#         batch_op.alter_column('queue_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)

#     with op.batch_alter_table('queues', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                autoincrement=True,
#                existing_server_default=sa.text("nextval('queues_id_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('queues_id_seq'::regclass)"))

    with op.batch_alter_table('extensiontoqueuelink', schema=None) as batch_op:
        batch_op.alter_column('queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('extension_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('call_data_records_details', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('call_week')

    with op.batch_alter_table('call_data_records', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
