"""Initial migration

Revision ID: ab98db2ffe5b
Revises: 
Create Date: 2024-11-30 16:37:05.965844

"""
from alembic import op
import sqlalchemy as sa
import os
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'ab98db2ffe5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    # Création de la table call_data_records si elle n'existe pas déjà
    if 'call_data_records' not in existing_tables:
        op.create_table('call_data_records',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('historyid', sa.String(), nullable=True),
            sa.Column('callid', sa.String(), nullable=True),
            sa.Column('duration', sa.Time(), nullable=True),
            sa.Column('time_start', sa.DateTime(), nullable=True),
            sa.Column('time_answered', sa.DateTime(), nullable=True),
            sa.Column('time_end', sa.DateTime(), nullable=True),
            sa.Column('reason_terminated', sa.String(), nullable=True),
            sa.Column('from_no', sa.String(), nullable=True),
            sa.Column('to_no', sa.String(), nullable=True),
            sa.Column('from_dn', sa.String(), nullable=True),
            sa.Column('to_dn', sa.String(), nullable=True),
            sa.Column('dial_no', sa.String(), nullable=True),
            sa.Column('reason_changed', sa.String(), nullable=True),
            sa.Column('final_number', sa.String(), nullable=True),
            sa.Column('final_dn', sa.String(), nullable=True),
            sa.Column('bill_code', sa.String(), nullable=True),
            sa.Column('bill_rate', sa.Float(), nullable=True),
            sa.Column('bill_cost', sa.Float(), nullable=True),
            sa.Column('bill_name', sa.String(), nullable=True),
            sa.Column('chain', sa.String(), nullable=True),
            sa.Column('from_type', sa.String(), nullable=True),
            sa.Column('to_type', sa.String(), nullable=True),
            sa.Column('final_type', sa.String(), nullable=True),
            sa.Column('from_dispname', sa.String(), nullable=True),
            sa.Column('to_dispname', sa.String(), nullable=True),
            sa.Column('final_dispname', sa.String(), nullable=True),
            sa.Column('missed_queue_calls', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_call_data_records')),
            sa.UniqueConstraint('callid', name=op.f('uq_call_data_records_callid')),
            sa.UniqueConstraint('historyid', name=op.f('uq_call_data_records_historyid'))
        )
    
    # Création de la table extensions si elle n'existe pas déjà
    if 'extensions' not in existing_tables:
        op.create_table('extensions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('extension', sa.String(length=255), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=True),
            sa.Column('mail', sa.String(length=255), nullable=True),
            sa.Column('date_added', sa.DateTime(), nullable=True),
            sa.Column('date_out', sa.DateTime(), nullable=True),
            sa.Column('out', sa.Integer(), nullable=True),
            sa.Column('date_modified', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_extensions'))
        )
        with op.batch_alter_table('extensions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_extensions_extension'), ['extension'], unique=True)
            batch_op.create_index(batch_op.f('ix_extensions_mail'), ['mail'], unique=False)
            batch_op.create_index(batch_op.f('ix_extensions_name'), ['name'], unique=False)

    # Création de la table extraevents si elle n'existe pas déjà
    if 'extraevents' not in existing_tables:
        op.create_table('extraevents',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('event_title', sa.String(), nullable=True),
            sa.Column('event_start', sa.DateTime(), nullable=True),
            sa.Column('event_end', sa.DateTime(), nullable=True),
            sa.Column('event_description', sa.String(), nullable=True),
            sa.Column('event_impact', sa.String(), nullable=False),
            sa.Column('date_added', sa.DateTime(), nullable=True),
            sa.Column('date_modified', sa.DateTime(), nullable=True),
            sa.Column('all_day', sa.Boolean(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_extraevents'))
        )

    # Création de la table queues si elle n'existe pas déjà
    if 'queues' not in existing_tables:
        op.create_table('queues',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('queue', sa.String(), nullable=True),
            sa.Column('queuename', sa.String(), nullable=True),
            sa.Column('date_added', sa.DateTime(), nullable=True),
            sa.Column('date_modified', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_queues'))
        )

    # Création de la table call_data_records_details si elle n'existe pas déjà
    if 'call_data_records_details' not in existing_tables:
        op.create_table('call_data_records_details',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('cdr_historyid', sa.String(), nullable=False),
            sa.Column('abandonned', sa.Boolean(), nullable=True),
            sa.Column('handling_time_seconds', sa.Integer(), nullable=True),
            sa.Column('waiting_time_seconds', sa.Integer(), nullable=True),
            sa.Column('call_date', sa.Date(), nullable=True),
            sa.Column('call_time', sa.Time(), nullable=True),
            sa.Column('call_week', sa.Integer(), nullable=True),
            sa.Column('day_of_week', sa.String(), nullable=True),
            sa.Column('filename', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['cdr_historyid'], ['call_data_records.historyid'], name=op.f('fk_call_data_records_details_cdr_historyid_call_data_records')),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_call_data_records_details'))
        )

    # Création de la table extensions_events si elle n'existe pas déjà
    if 'extensions_events' not in existing_tables:
        op.create_table('extensions_events',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('extension_id', sa.Integer(), nullable=False),
            sa.Column('event_id', sa.Integer(), nullable=False),
            sa.Column('date_added', sa.DateTime(), nullable=True),
            sa.Column('date_modified', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['event_id'], ['extraevents.id'], name=op.f('fk_extensions_events_event_id_extraevents')),
            sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], name=op.f('fk_extensions_events_extension_id_extensions')),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_extensions_events'))
        )

    # Création de la table extensiontoqueuelink si elle n'existe pas déjà
    if 'extensiontoqueuelink' not in existing_tables:
        op.create_table('extensiontoqueuelink',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('extension_id', sa.Integer(), nullable=False),
            sa.Column('queue_id', sa.Integer(), nullable=False),
            sa.Column('date_added', sa.DateTime(), nullable=True),
            sa.Column('date_modified', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], name=op.f('fk_extensiontoqueuelink_extension_id_extensions')),
            sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_extensiontoqueuelink_queue_id_queues')),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_extensiontoqueuelink'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extensiontoqueuelink')
    op.drop_table('extensions_events')
    op.drop_table('call_data_records_details')
    op.drop_table('queues')
    op.drop_table('extraevents')
    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extensions_name'))
        batch_op.drop_index(batch_op.f('ix_extensions_mail'))
        batch_op.drop_index(batch_op.f('ix_extensions_extension'))

    op.drop_table('extensions')
    op.drop_table('call_data_records')
    # ### end Alembic commands ###