"""ajout uncité sur extensions

Revision ID: b48138200c75
Revises: 8a7b8d52900c
Create Date: 2024-06-29 17:41:46.096536

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b48138200c75'
down_revision = '8a7b8d52900c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('out',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_index('ix_extensions_extension')
        batch_op.create_index(batch_op.f('ix_extensions_extension'), ['extension'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extensions_extension'))
        batch_op.create_index('ix_extensions_extension', ['extension'], unique=False)
        batch_op.alter_column('out',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
