"""add recurrence rules to events

Revision ID: bd81eaa71511
Revises: 6b4ef429c085
Create Date: 2025-02-22 15:38:22.073346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'bd81eaa71511'
down_revision = '6b4ef429c085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Vérifier si la colonne existe déjà avant de l'ajouter
    columns = [col['name'] for col in inspector.get_columns('extraevents')]
    if 'recurrence_rule' not in columns:
        with op.batch_alter_table('extraevents', schema=None) as batch_op:
            batch_op.add_column(sa.Column('recurrence_rule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.drop_column('recurrence_rule')
    # ### end Alembic commands ###