"""modif events table ajout jour entier

Revision ID: bfe2413e87ef
Revises: 043ad3698baf
Create Date: 2024-08-14 18:56:26.378517

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bfe2413e87ef'
down_revision = '043ad3698baf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.drop_column('all_day')

    # ### end Alembic commands ###
