"""Add news

Revision ID: d4916a1a976e
Revises: c2e81050096a
Create Date: 2024-08-12 17:47:30.748478

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4916a1a976e'
down_revision = 'c2e81050096a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
