"""Ajout table files, extensions et detail cdr

Revision ID: df10cb5cf782
Revises: edab82d9edcb
Create Date: 2022-07-29 17:46:24.884950

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'df10cb5cf782'
down_revision = 'edab82d9edcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=False),
    sa.Column('sorti', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queuename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_data_records_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdr_id', sa.Integer(), nullable=True),
    sa.Column('abandonned', sa.Boolean(), nullable=False),
    sa.Column('handling_time', sa.Time(), nullable=False),
    sa.Column('waiting_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['cdr_id'], ['call_data_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extensiontoqueuelink',
    sa.Column('estension_id', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estension_id'], ['extensions.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('estension_id', 'queue_id')
    )
    op.alter_column('call_data_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_data_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_table('extensiontoqueuelink')
    op.drop_table('call_data_records_details')
    op.drop_table('queues')
    op.drop_table('extensions')
    # ### end Alembic commands ###
