"""modif events table

Revision ID: 043ad3698baf
Revises: 4f38c31ac5e0
Create Date: 2024-08-14 17:01:14.245875

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '043ad3698baf'
down_revision = '4f38c31ac5e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('event_explanation')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraevents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('event_description')

    # ### end Alembic commands ###
