"""Modification champs table 3cxcdr

Revision ID: 08d390588f18
Revises: ba77f723cb5f
Create Date: 2023-06-07 10:39:41.953712

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08d390588f18'
down_revision = 'ba77f723cb5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_data_records', schema=None) as batch_op:
        batch_op.alter_column('reason_terminated',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('from_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('to_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('from_dn',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('to_dn',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dial_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('reason_changed',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('final_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('final_dn',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bill_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bill_rate',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bill_cost',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bill_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('chain',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('from_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('to_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('final_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('from_dispname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('to_dispname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('final_dispname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('missed_queue_calls',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('call_data_records_details', schema=None) as batch_op:
        batch_op.alter_column('cdr_historyid',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_data_records_details', schema=None) as batch_op:
        batch_op.alter_column('cdr_historyid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('call_data_records', schema=None) as batch_op:
        batch_op.alter_column('missed_queue_calls',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('final_dispname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('to_dispname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('from_dispname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('final_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('to_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('from_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('chain',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('bill_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('bill_cost',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('bill_rate',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('bill_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('final_dn',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('final_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('reason_changed',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('dial_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('to_dn',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('from_dn',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('to_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('from_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('reason_terminated',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
