"""Add events table

Revision ID: ae67969701ee
Revises: d4916a1a976e
Create Date: 2024-08-12 18:25:12.620713

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae67969701ee'
down_revision = 'd4916a1a976e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraevents',
    sa.Column('event_tile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.Column('event_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraevents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraevents')
    # ### end Alembic commands ###
