"""Modification type  semaine d'appel

Revision ID: ba77f723cb5f
Revises: 878e19eed77b
Create Date: 2023-06-06 15:09:46.643328

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba77f723cb5f'
down_revision = '878e19eed77b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_data_records', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('call_data_records_id_seq'::regclass)"))

    with op.batch_alter_table('call_data_records_details', schema=None) as batch_op:
        batch_op.alter_column('call_week',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('extensions_id_seq'::regclass)"))

    with op.batch_alter_table('extensiontoqueuelink', schema=None) as batch_op:
        batch_op.alter_column('extension_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('extensiontoqueuelink', schema=None) as batch_op:
        batch_op.alter_column('queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('extension_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('extensions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('extensions_id_seq'::regclass)"))

    with op.batch_alter_table('call_data_records_details', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('call_week',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('call_data_records', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('call_data_records_id_seq'::regclass)"))

    # ### end Alembic commands ###
