"""Ajout day of week

Revision ID: c23c03b391d0
Revises: ec61e94907d6
Create Date: 2022-08-30 09:33:18.748590

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c23c03b391d0'
down_revision = 'ec61e94907d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('call_data_records_details', sa.Column('day_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('call_data_records_details', 'day_of_week')

    # ### end Alembic commands ###
