"""Ajout de champs dans les complements de cdr

Revision ID: ec61e94907d6
Revises: 9fd4ad31c31d
Create Date: 2022-08-23 00:37:16.290160

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ec61e94907d6'
down_revision = '9fd4ad31c31d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_data_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'call_data_records', ['callid'])
    op.add_column('call_data_records_details', sa.Column('call_date', sa.Date(), nullable=False))
    op.add_column('call_data_records_details', sa.Column('call_time', sa.Time(), nullable=False))
    op.alter_column('call_data_records_details', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('extensions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('extensiontoqueuelink', 'extension_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extensiontoqueuelink', 'queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('queues', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queues', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('extensiontoqueuelink', 'queue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extensiontoqueuelink', 'estension_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extensions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('call_data_records_details', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('call_data_records_details', 'call_time')
    op.drop_column('call_data_records_details', 'call_date')
    op.drop_constraint(None, 'call_data_records', type_='unique')
    op.alter_column('call_data_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
