"""1ere revision

Revision ID: edab82d9edcb
Revises:
Create Date: 2022-07-28 00:08:38.187704

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'edab82d9edcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_data_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historyid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_answered', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('reason_terminated', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_dn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_dn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_changed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_dn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bill_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bill_rate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bill_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bill_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_dispname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_dispname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_dispname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missed_queue_calls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('historyid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_data_records')
    # ### end Alembic commands ###
