"""Ajout colonne sauvegarde nom fichier csv

Revision ID: ef1bbaa2f981
Revises: 08d390588f18
Create Date: 2024-05-03 16:27:58.556733

"""

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "ef1bbaa2f981"
down_revision = "08d390588f18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("call_data_records_details", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.alter_column(
            "call_week",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="call_week::INTEGER",
        )

    with op.batch_alter_table("extensions", schema=None) as batch_op:
        (batch_op.add_column(sa.Column("out", sa.Boolean(), nullable=True)),)
        batch_op.alter_column("date_added", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column("out", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("extensions", schema=None) as batch_op:
        batch_op.alter_column("out", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("date_added", existing_type=sa.DATE(), nullable=True)

    with op.batch_alter_table("call_data_records_details", schema=None) as batch_op:
        batch_op.alter_column(
            "call_week",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )
        batch_op.drop_column("filename")

    # ### end Alembic commands ###
